### ISSUE TITLE
from darkgreybox.models import ... fails

### ISSUE THREAD

**Issue by hussainkazmi** [czagoni/darkgreybox#24]
Hi,
Thank you for the very interesting library. However, I cannot run the tutorials after pip installing the package (both the dev branch and otherwise) as it crashes with the following message:
No module named 'darkgreybox.models'
I was able to reproduce the issue on two independent machines so it seems there is a problem with the package. Can you please take a look?
Thanks!

**Comment by czagoni** [comment]
Hi @hussainkazmi ,

Sorry for not getting back to you sooner.

I believe this is due to a confusion in the readme: there are two different methods of installation and mixing the two results in unexpected behaviour.

If you could try the following:
* create a new virtualenv
* clone the package from github
* install dependencies: `pip install -e .'[dev,test]'`

The tutorials should be now inline with the package source. 
I've updated the readme to clarify this - please let me know how it works for you!

**Comment by hussainkazmi** [comment]
Hi, thanks for the fix! I can run the models now. However the tutorial notebook is still throwing an exception when I run the following statement:
from docs.tutorials.util.plot import plot, plot_input_data
Here is the exception:
ModuleNotFoundError: No module named 'docs.tutorials'
Not sure if this is an issue with the library or my installation though :)

**Comment by czagoni** [comment]
Hi @hussainkazmi ,

I cannot reproduce the error you are getting...

Could you double check that you are using a new, clean virtualenvironment, cloned the latest master branch from github and installed the dependencies as required? 

You should see `darkgreybox` listed when you do `pip list` and you could also check that you are launching the right jupyter that is in your virtualenv. 

If the problem persists, would you mind providing more info on your setup please?
